description: "Contains Wind Turbine Power Generation Measurements"

# Target
target:
  name: turbine
  catalog: silver
  schema: c_source_h
  mode: merge
  format: delta
  table_schema:
    timestamp:
      type: timestamp
      is_primary_key: true
    turbine_id:
      type: integer
      is_primary_key: true
    wind_speed:
      type: decimal(5,2)
    wind_direction:
      type: integer
    power_output:
      type: decimal(5,2)