description: "Contains Daily Wind Turbine Performance Summary Statistics and Anomaly Detection Results"

# Target
target:
  name: turbine_measurement_summary
  catalog: gold
  schema: b_source_h
  mode: merge
  format: delta
  table_schema:
    turbine_id:
      type: integer
      is_primary_key: true

    date:
      type: date
      is_primary_key: true

    min_power:
      type: decimal(10,4)

    max_power:
      type: decimal(10,4)

    avg_power:
      type: decimal(10,4)

    stddev_power:
      type: decimal(10,4)

    is_anomaly:
      type: boolean

# Sources
sources:
  - name: turbine_measurement
    catalog: silver
    schema: b_source_h
    format: delta